name: Build XNU Darwin Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: make
      run: sudo xcode-select install
    - uses: actions/checkout@v3
    - name: make
      run: make SDKROOT=/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk ARCH_CONFIGS=X86_64 KERNEL_CONFIGS="RELEASE"
